### PR TITLE
BP-1114 Magento 2 - Remove skip_push logic

### PR DESCRIPTION
**Pull request by vladislav-padalka-hys**

### CODE REVIEW

**Comment by florinel-chis** [comment]
@vladislav-padalka-hys 
Just to confirm - we need to keep skip_push in these ones:
```
Model/Push.php:        $skipFirstPush = $payment->getAdditionalInformation('skip_push');
Model/Push.php:            $payment->setAdditionalInformation('skip_push', $skipFirstPush - 1);
Model/Method/Billink.php:        $payment->setAdditionalInformation('skip_push', 1);
Model/Method/Billink.php:        $payment->setAdditionalInformation('skip_push', 1);
Model/Method/SepaDirectDebit.php:            $payment->setAdditionalInformation('skip_push', 2);
Model/Method/Transfer.php:                'skip_push',
Model/Method/AbstractMethod.php:            $skipFirstPush = $payment->getAdditionalInformation('skip_push');
Model/Method/AbstractMethod.php:                $payment->setAdditionalInformation('skip_push', $skipFirstPush - 1);
Model/Method/Creditcards.php:            $payment->setAdditionalInformation('skip_push', 2);
Model/Method/PayLink.php:                'skip_push',
Model/Method/Afterpay.php:            $payment->setAdditionalInformation('skip_push', 1);
Model/Method/Afterpay20.php:            $payment->setAdditionalInformation('skip_push', 1);
```

**Comment by vladislav-padalka-hys** [comment]
> @vladislav-padalka-hys Just to confirm - we need to keep skip_push in these ones:
> 
> ```
> Model/Push.php:        $skipFirstPush = $payment->getAdditionalInformation('skip_push');
> Model/Push.php:            $payment->setAdditionalInformation('skip_push', $skipFirstPush - 1);
> Model/Method/Billink.php:        $payment->setAdditionalInformation('skip_push', 1);
> Model/Method/Billink.php:        $payment->setAdditionalInformation('skip_push', 1);
> Model/Method/SepaDirectDebit.php:            $payment->setAdditionalInformation('skip_push', 2);
> Model/Method/Transfer.php:                'skip_push',
> Model/Method/AbstractMethod.php:            $skipFirstPush = $payment->getAdditionalInformation('skip_push');
> Model/Method/AbstractMethod.php:                $payment->setAdditionalInformation('skip_push', $skipFirstPush - 1);
> Model/Method/Creditcards.php:            $payment->setAdditionalInformation('skip_push', 2);
> Model/Method/PayLink.php:                'skip_push',
> Model/Method/Afterpay.php:            $payment->setAdditionalInformation('skip_push', 1);
> Model/Method/Afterpay20.php:            $payment->setAdditionalInformation('skip_push', 1);
> ```

correct , it's expected

**Review by florinel-chis — APPROVED** [review]

**Comment by Buckaroo-Rens** [comment]
Just a double check, is it also expected in Model/Method/SepaDirectDebit.php, Model/Method/Transfer.php & Model/Method/PayLink.php sincei tought it was only expected in Billink & AfterPay.

**Comment by vladislav-padalka-hys** [comment]
yes, for mentioned methods it's legacy support of CM kept
but for usual workflow (w/o CM) no skip logic will be

**Pull request merged**
