### PR TITLE
[BP-544] Added additional attributes to CreditmemoInterface.

### PR DESCRIPTION
**Pull request by jvanschie**
Added extension attributes to CreditmemoInterface.

Did this to be able to retrieve the extension attributes from the API (SalesCreditmemoRepositoryV1Api).

### CODE REVIEW

**Comment by jvanschie** [comment]
Hello, can someone please review this?

**Comment by Buckaroo-Rens** [comment]
@jvanschie Sorry, i totally missed this request. I will try to plan a review beginning of next week.

**Comment by Buckaroo-Rens** [comment]
We made some changes, based on your request. Those can be found here: https://github.com/buckaroo-it/Magento2/commit/3dfe9f6bcb9344777899bfede2175d65643b70c2 and are also released in v1.29.0

**Comment by jvanschie** [comment]
@Buckaroo-Rens thank you

**Pull request closed without merging**
