### PR TITLE
BP-659 phpcs workflow

### PR DESCRIPTION
**Pull request by florinel-chis**

### CODE REVIEW

**Comment by vladislav-padalka-hys** [comment]
@florinel-chis can we rename Buckaroo's plugin directory extracted to Buckaroo instead of Magento2 , because paths like .../Magento2/Magento2/Api/PaymentInformationManagementInterface.php are confused a bit

**Comment by vladislav-padalka-hys** [comment]
and more general thing : do we need to create magento project each time if we need to simply check our plugin code , so it can be done quicker like 
composer require squizlabs/php_codesniffer:^3.4
composer require magento/magento-coding-standard
vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/
vendor/bin/phpcs --standard='Magento2 PATH TO BUCKAROO PLUGIN'

**Comment by vladislav-padalka-hys** [comment]
again, why to fetch each time CS ? 

>>get phpcs
>>        run: |
>>          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

why just not install it one time using by composer and then update only if needed ?

**Comment by florinel-chis** [comment]
@vladislav-padalka-hys do have a look at https://github.com/features/actions

**Comment by florinel-chis** [comment]
> and more general thing : do we need to create magento project each time if we need to simply check our plugin code , so it can be done quicker like
> composer require squizlabs/php_codesniffer:^3.4
> composer require magento/magento-coding-standard
> vendor/bin/phpcs --config-set installed_paths ../../magento/magento-coding-standard/
> vendor/bin/phpcs --standard='Magento2 PATH TO BUCKAROO PLUGIN'

I believe the current approach is sufficient. Regarding the suggested changes, please open a PR with the proposed approach.

**Pull request closed without merging**
