### PR TITLE
Feature/bp 708 log admin

### PR DESCRIPTION
**Pull request by florinel-chis**

### CODE REVIEW

**Review by saranchuk-hys — APPROVED** [review]

**Review by vladislav-padalka-hys — COMMENTED** [review]
in many places there are specified in phpdoc 
@param string $orderId
but it's not proper
actually there is no sense in such phpdoc statements
IMO we need use native types for incoming/outgoing parameteres 
PHP 7.3 is minimum

**Comment by florinel-chis** [comment]
@vladislav-padalka-hys can you please elaborate on this, more specific, what you are referring to? we should make use of native strict types?

**Comment by vladislav-padalka-hys** [comment]
if it's not clear , then here is specific example of wrong type in phpdoc 
https://github.com/buckaroo-it/Magento2/pull/145/commits/55913e671224ebba9bf5038312211aba229b226a#diff-df59f0c4ab6c43fb7868c9209a9f2c567b21ca646195b206f8f9f2c7c8ea28c0R137
it should be int

also, I still think that it better to write 
public function setQuoteId(int $quoteId);
instead 
@param int $orderId

**Comment by florinel-chis** [comment]
@vladislav-padalka-hys 

- create an instance for the collection (or the model)
- retrieve one record
- check the returned type for each field

at the moment, we don't use strict types for this part and this should be part of a larger conversation.

**Comment by vladislav-padalka-hys** [comment]
I've totally confused with your answer about string->int change

if you would like to note in phpdoc that we need to pass string for order or quote id then it's ok , but in real life it's an int
just check magento's db
CREATE TABLE `sales_order` (
  `entity_id` int(10)

usage of strict type is separate thing and I'm not about it now
I'm about usage of types for method arguments
Strange that you can not understand ,e especially if you already do this like in 
https://github.com/buckaroo-it/Magento2/pull/145/commits/55913e671224ebba9bf5038312211aba229b226a#diff-3e9c6d3e16f515b4bbd7bd9f382ec299bbd69f883670654bc064f529344d86bfR24
so why you don't want to make it consistent in all places ?

**Comment by florinel-chis** [comment]
@vladislav-padalka-hys  In order to align and be on the same page and understand why the phpdoc is with string and not int, I provided the steps so that you can have clarity on it.

**Pull request merged**
